assets/css/main.scss, components/MessageModal.vue, pages/messages.vue, pages/messages/index.vue
* Fix Compose modal trigger
* Update dark mode CSS for `/messages` changes
* Rename "Public Rooms" to "Chat Rooms" (they aren't all public)
=> Fix modal, update dark mode styling

components/Channel.vue, components/ChannelCompose.vue, components/Header.vue, components/MessageCompose.vue, components/sidebar/App.js, pages/about/index.vue, pages/messages/_channel.vue
=> Improve layout

nuxt.config.js
- Enable http2 server push
- Remove unnecessary settings
=> Improve config

__tests__/assets/js/util.spec.js, assets/js/util.js, pages/at_name/index.vue, pages/tags/_name.vue
=> Add feed url to head

__tests__/components/EntityText.spec.js, __tests__/components/NuxtLinkMod.spec.js, components/EntityText.vue, components/NuxtLinkMod.vue, components/Profile.vue, nuxt.config.js, pages/messages.vue
=> Replace patter links 191

.eslintignore, .eslintrc.js, __tests__/assets/js/util.spec.js, __tests__/components/Avatar.spec.js, __tests__/setup.js, assets/js/mark-as-read.js, assets/js/util.js, components/AclSelect.vue, components/Avatar.vue, components/BaseModal.vue, components/Channel.vue, components/ChannelCompose.vue, components/ChannelEditModal.vue, components/ChannelMemberEditModal.vue, components/ChannelPanel.vue, components/ChatPanel.js, components/Compose.vue, components/List.vue, components/MessageCompose.vue, components/Profile.vue, pages/messages/_channel.vue, pages/posts/_id.vue, pages/posts/_id/revisions.vue
=> Fix modals of channel pages

pages/at_name/index.vue
Fix #205 
Sorry :bow::bow::bow:
=> Fix RSS URL

__tests__/components/PostModal.spec.js, assets/js/util.js, components/BaseModal.vue, components/Compose.vue, components/PostModal.vue
=> Fix reply modal 203

__tests__/components/Profile.spec.js, components/Profile.vue
=> Fix the dropdown in Profile

__tests__/axios-mock.js, __tests__/components/List.spec.js, __tests__/setup.js, components/List.vue
=> Fix refreshing error in list

__tests__/components/Avatar.spec.js, components/Avatar.vue
=> Support retina

pages/messages/_channel.vue
=> Be able to view public channel without logged in

__tests__/axios-mock.js, __tests__/components/Profile.spec.js, __tests__/fixtures/channel.js, __tests__/fixtures/index.js, __tests__/fixtures/user.js, __tests__/helper.js, components/CreatePmModal.vue, components/MessageCompose.vue, components/MessageModal.vue, components/Profile.vue, components/file-list.vue, layouts/default.vue, plugins/axios/index.js, plugins/font-awesome.js
=> Add message button 169

__tests__/components/sidebar/App.spec.js, components/sidebar/App.js, layouts/default.vue, pages/global.vue, pages/index.vue, plugins/axios/resources.js
=> Show global 145

__tests__/axios-mock.js, __tests__/components/MessageCompose.spec.js, __tests__/fixtures/channel.js, assets/js/util.js, components/MessageCompose.vue, components/Post.vue, package.json, pages/messages/_channel.vue, yarn.lock
=> Add broadcast button 219

pages/messages.vue
=> Hide messages tab

components/Channel.vue, components/ChannelList.vue
=> Fix duplicate 236

__tests__/components/Avatar.spec.js, assets/css/main.scss, assets/js/util.js, components/Avatar.vue, components/ChannelUserList.vue, components/Message.vue, pages/messages/_channel.vue
=> Handling deleted user 244

__tests__/components/EntityText.spec.js, __tests__/components/Post.spec.js, __tests__/fixtures/post.js, components/BaseList.vue, components/BaseModal.vue, components/Compose.vue, components/EntityText.vue, components/Post.vue, components/PostList.vue, components/PostModal.vue, plugins/modal/PromiseModal.vue, plugins/modal/mediator.js
=> Implement post editing

__tests__/components/Nsfw.spec.js, components/Channel.vue, components/Compose.vue, components/Nsfw.vue, components/Post.vue, plugins/emojify/Emojify.vue, plugins/font-awesome.js
=> Implement NSFW handling

assets/js/oembed.js, assets/js/util.js, components/Compose.vue, components/Interaction.vue, components/Post.vue, layouts/error.vue, pages/posts/_id.vue, plugins/axios/index.js
=> Fix small issues

components/settings/Stream.vue, components/sidebar/Settings.vue, pages/conversations.vue, pages/global.vue, pages/index.vue, pages/mentions.vue, pages/missed-conversations.vue, pages/newcomers.vue, plugins/axios/index.js, yarn.lock
Add these options:
* unified stream
* directed posts
=> Add stream settings

assets/js/util.js, components/Post.vue
=> Fix wrong behavior when tried to show embedded video

__tests__/components/Avatar.spec.js, components/Avatar.vue, components/BaseList.vue, components/Channel.vue
=> Fix user list
